# Generated by Django 4.2.10 on 2025-04-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivitiesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("status", models.BooleanField(default=True, verbose_name="progress")),
                ("keywords", models.CharField(default="", max_length=200)),
                ("description", models.CharField(default="", max_length=200)),
                ("slug", models.SlugField(default="", unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
