# Generated by Django 4.2.10 on 2025-04-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitiesmodel",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
