# Generated by Django 5.1.6 on 2025-02-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitiesmodel",
            name="description",
            field=models.CharField(default="default description", max_length=200),
        ),
        migrations.AddField(
            model_name="activitiesmodel",
            name="keywords",
            field=models.CharField(default="default keyword", max_length=200),
        ),
        migrations.AddField(
            model_name="activitiesmodel",
            name="slug",
            field=models.SlugField(default="defaultslug", unique=True),
        ),
    ]
