# Generated by Django 4.2.10 on 2025-04-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_alter_activitiesmodel_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitiesmodel",
            name="description",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="activitiesmodel",
            name="keywords",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
