# Generated by Django 5.1.6 on 2025-02-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "activities",
            "0002_activitiesmodel_description_activitiesmodel_keywords_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitiesmodel",
            name="description",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="activitiesmodel",
            name="keywords",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="activitiesmodel",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
        migrations.AlterField(
            model_name="activitiesmodel",
            name="status",
            field=models.BooleanField(default=True, verbose_name="progress"),
        ),
    ]
