# Generated by Django 4.2.10 on 2025-03-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_alter_activitiesmodel_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitiesmodel",
            name="image",
        ),
    ]
