# Generated by Django 5.1.6 on 2025-02-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facilities",
            name="image",
        ),
    ]
