# Generated by Django 5.1.6 on 2025-02-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0002_remove_facilities_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facilities",
            old_name="is_status",
            new_name="status",
        ),
    ]
