# Generated by Django 5.1.6 on 2025-02-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0003_rename_is_status_facilities_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilities",
            name="status",
            field=models.BooleanField(default=True, verbose_name="progress"),
        ),
    ]
