# Generated by Django 4.2.10 on 2025-03-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0005_alter_facilities_content_alter_facilities_heading"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facilities",
            name="icon",
        ),
    ]
