# Generated by Django 4.2.10 on 2025-04-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0005_alter_facilities_content_alter_facilities_heading"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facilities",
            name="icon",
        ),
        migrations.AlterField(
            model_name="facilities",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="facilities",
            name="heading",
            field=models.CharField(max_length=200),
        ),
    ]
