# Generated by Django 4.2.10 on 2025-04-02 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_icon"),
        ("facilities", "0006_remove_facilities_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilities",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.icon",
            ),
        ),
    ]
