# Generated by Django 4.2.10 on 2025-04-16 04:35

import common.models
import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("icon", "Icon")],
                        max_length=10,
                        validators=[common.validators.validation_media],
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=common.models.upload_to_media,
                        validators=[common.validators.validate_file],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[common.validators.validate_name_length],
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "size",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[common.validators.validate_image_size],
                    ),
                ),
                (
                    "custom_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "original_file_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[common.validators.validate_alt_text],
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[common.validators.validate_caption],
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "relation_type",
                    models.CharField(
                        choices=[("main_image", "Main Image"), ("icon", "Icon")],
                        default="main_image",
                        max_length=20,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.image"
                    ),
                ),
            ],
        ),
    ]
