# Generated by Django 4.2.10 on 2025-03-31 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagecontent",
            old_name="image_id",
            new_name="image",
        ),
    ]
