# Generated by Django 4.2.10 on 2025-04-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_rename_image_id_imagecontent_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagecontent",
            name="image",
        ),
        migrations.AddField(
            model_name="imagecontent",
            name="url",
            field=models.ImageField(default="", upload_to="images/"),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
