# Generated by Django 4.2.10 on 2025-04-01 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_remove_imagecontent_image_imagecontent_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="imagecontent",
            name="url",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.image"
            ),
        ),
    ]
