# Generated by Django 4.2.10 on 2025-04-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_image_alter_imagecontent_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="updated_at",
            new_name="uploaded_at",
        ),
        migrations.RenameField(
            model_name="imagecontent",
            old_name="url",
            new_name="image",
        ),
    ]
