# Generated by Django 4.2.10 on 2025-04-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_rename_updated_at_image_uploaded_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Icon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("icon_file", models.ImageField(upload_to="icons/")),
            ],
        ),
    ]
