# Generated by Django 5.1.6 on 2025-03-19 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_contactmodel_email_alter_contactmodel_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmodel",
            name="message",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="contactmodel",
            name="name",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.RegexValidator(
                        message="Name must contan only letter and spaces ",
                        regex="^[a-zA-z\\s]*$",
                    ),
                ],
            ),
        ),
    ]
