# Generated by Django 5.1.6 on 2025-03-19 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_alter_aboutmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutmodel",
            name="content",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(10)]
            ),
        ),
        migrations.AlterField(
            model_name="aboutmodel",
            name="heading",
            field=models.CharField(
                max_length=200,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
    ]
