# Generated by Django 5.1.6 on 2025-02-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careermodel",
            name="status",
            field=models.BooleanField(default=True, verbose_name="progress"),
        ),
    ]
