# Generated by Django 4.2.10 on 2025-04-24 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quote",
                    models.TextField(
                        help_text="Enter a quote (max 150 characters)",
                        validators=[django.core.validators.MaxLengthValidator(150)],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the person ", max_length=100
                    ),
                ),
                ("designation", models.CharField(blank=True, max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, unique=True, upload_to="testimonials/"
                    ),
                ),
                ("is_active", models.BooleanField(default="True")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
