# Generated by Django 4.2.10 on 2025-04-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testimonials",
            old_name="is_active",
            new_name="is_featured",
        ),
    ]
