# Generated by Django 5.1.6 on 2025-02-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
