# Generated by Django 5.1.6 on 2025-02-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0003_rename_is_status_hero_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="status",
            field=models.BooleanField(default=True, verbose_name="progress"),
        ),
    ]
