# Generated by Django 4.2.10 on 2025-03-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0005_alter_hero_content_alter_hero_heading"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hero",
            name="image",
        ),
    ]
