# Generated by Django 4.2.10 on 2025-04-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0005_alter_hero_content_alter_hero_heading"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hero",
            name="image",
        ),
        migrations.AlterField(
            model_name="hero",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="hero",
            name="heading",
            field=models.CharField(max_length=200),
        ),
    ]
